Repro of target continuing to run after compiler error
"C:\Users\jopepper\Desktop\Git\MSBuildIncrementalClean\Foo.csproj" (default target) (1) ->
(CoreCompile target) ->
  Foo.cs(2,15): error CS0116: A namespace cannot directly contain members such as fields or methods [C:\Users\jopepper\Desktop\Git\MSBuildIncrementalClean\Foo.csproj]
  Foo.cs(2,15): error CS0548: '<invalid-global-code>.Foo': property or indexer must have at least one accessor [C:\Users\jopepper\Desktop\Git\MSBuildIncrementalClean\Foo.csproj]
  Foo.cs(2,8): error CS0246: The type or namespace name 'classy' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\jopepper\Desktop\Git\MSBuildIncrementalClean\Foo.csproj]

"C:\Users\jopepper\Desktop\Git\MSBuildIncrementalClean\Foo.csproj" (default target) (1) ->
(_CompileDex target) ->
  C:\Users\jopepper\Desktop\Git\MSBuildIncrementalClean\Xamarin.Android.targets(42,5): error : This is another error you should *not* see! [C:\Users\jopepper\Desktop\Git\MSBuildIncrementalClean\Foo.csproj]

    0 Warning(s)
    4 Error(s)